import app from "./app.js";
import dotenv from "dotenv";
import connectDB from "./config/db.js";
import "./config/redis.js";
import logger from "./config/logger.js";
import {
  bulkUpsertCities,
  initCityCache,
} from "./modules/places/services/city.service.js";
import {
  bulkUpsertAirports,
  initAirportCache,
} from "./modules/flights/services/airport.service.js";
import { startCronJobs } from "./cron/index.js";
import { readFile } from "fs/promises";

dotenv.config();

async function start() {
  await connectDB();
  await initAirportCache();
  try {
    const citiesJson = JSON.parse(
      await readFile(
        new URL("./modules/places/data/cities.json", import.meta.url),
      ),
    );
    const STATE_MAP = {
      Chennai: "Tamil Nadu",
      Coimbatore: "Tamil Nadu",
      Madurai: "Tamil Nadu",
      Salem: "Tamil Nadu",
      Erode: "Tamil Nadu",
      Tiruppur: "Tamil Nadu",
      Tirunelveli: "Tamil Nadu",
      Trichy: "Tamil Nadu",
      Villupuram: "Tamil Nadu",
      Kanyakumari: "Tamil Nadu",
      Dharapuram: "Tamil Nadu",
      Sivagangai: "Tamil Nadu",
      Dindigul: "Tamil Nadu",
      Thanjavur: "Tamil Nadu",
      Vellore: "Tamil Nadu",
      Ramagundam: "Tamil Nadu",
      Tiruvottiyur: "Tamil Nadu",
      Nagercoil: "Tamil Nadu",
      Thoothukudi: "Tamil Nadu",
      Tiruvannamalai: "Tamil Nadu",
      Bangalore: "Karnataka",
      Bengaluru: "Karnataka",
      Mysore: "Karnataka",
      "Hubli-Dharwad": "Karnataka",
      Mangalore: "Karnataka",
      Belgaum: "Karnataka",
      Davanagere: "Karnataka",
      Bellary: "Karnataka",
      Gulbarga: "Karnataka",
      Shivamogga: "Karnataka",
      Tumkur: "Karnataka",
      Bijapur: "Karnataka",
      Hyderabad: "Telangana",
      Visakhapatnam: "Andhra Pradesh",
      Vijayawada: "Andhra Pradesh",
      Guntur: "Andhra Pradesh",
      Nellore: "Andhra Pradesh",
      Kurnool: "Andhra Pradesh",
      Rajahmundry: "Andhra Pradesh",
      Kakinada: "Andhra Pradesh",
      Nizamabad: "Telangana",
      Khammam: "Telangana",
      Karimnagar: "Telangana",
      Warangal: "Telangana",
      Anantapur: "Andhra Pradesh",
      Tenali: "Andhra Pradesh",
      Eluru: "Andhra Pradesh",
      Vijayanagaram: "Andhra Pradesh",
      Mumbai: "Maharashtra",
      Pune: "Maharashtra",
      Nagpur: "Maharashtra",
      Nashik: "Maharashtra",
      Thane: "Maharashtra",
      Aurangabad: "Maharashtra",
      Solapur: "Maharashtra",
      Amravati: "Maharashtra",
      Nanded: "Maharashtra",
      Kolhapur: "Maharashtra",
      Jalgaon: "Maharashtra",
      Malegaon: "Maharashtra",
      Dhule: "Maharashtra",
      Jalna: "Maharashtra",
      Chandrapur: "Maharashtra",
      Latur: "Maharashtra",
      Parbhani: "Maharashtra",
      Bhiwandi: "Maharashtra",
      "Navi Mumbai": "Maharashtra",
      "Pimpri-Chinchwad": "Maharashtra",
      "Vasai-Virar": "Maharashtra",
      Ahmednagar: "Maharashtra",
      Satara: "Maharashtra",
      Ichalkaranji: "Maharashtra",
      Ambernath: "Maharashtra",
      Ulhasnagar: "Maharashtra",
      Bhilwara: "Maharashtra",
      Ahmedabad: "Gujarat",
      Surat: "Gujarat",
      Vadodara: "Gujarat",
      Rajkot: "Gujarat",
      Bhavnagar: "Gujarat",
      Jamnagar: "Gujarat",
      Junagadh: "Gujarat",
      Gandhidham: "Gujarat",
      Delhi: "Delhi",
      "New Delhi": "Delhi",
      Noida: "Uttar Pradesh",
      Ghaziabad: "Uttar Pradesh",
      Faridabad: "Haryana",
      Gurgaon: "Haryana",
      Lucknow: "Uttar Pradesh",
      Kanpur: "Uttar Pradesh",
      Agra: "Uttar Pradesh",
      Varanasi: "Uttar Pradesh",
      Allahabad: "Uttar Pradesh",
      Meerut: "Uttar Pradesh",
      Bareilly: "Uttar Pradesh",
      Moradabad: "Uttar Pradesh",
      Saharanpur: "Uttar Pradesh",
      Gorakhpur: "Uttar Pradesh",
      Aligarh: "Uttar Pradesh",
      Jodhpur: "Rajasthan",
      Firozabad: "Uttar Pradesh",
      Mathura: "Uttar Pradesh",
      Rampur: "Uttar Pradesh",
      Shahjahanpur: "Uttar Pradesh",
      Budaun: "Uttar Pradesh",
      Hapur: "Uttar Pradesh",
      Bulandshahr: "Uttar Pradesh",
      Etawah: "Uttar Pradesh",
      Mau: "Uttar Pradesh",
      Farrukhabad: "Uttar Pradesh",
      Mirzapur: "Uttar Pradesh",
      Banda: "Uttar Pradesh",
      Akbarpur: "Uttar Pradesh",
      Jaipur: "Rajasthan",
      Udaipur: "Rajasthan",
      Kota: "Rajasthan",
      Bikaner: "Rajasthan",
      Ajmer: "Rajasthan",
      Bharatpur: "Rajasthan",
      Alwar: "Rajasthan",
      Sikar: "Rajasthan",
      Pali: "Rajasthan",
      "Sri Ganganagar": "Rajasthan",
      Ratlam: "Madhya Pradesh",
      Bhopal: "Madhya Pradesh",
      Indore: "Madhya Pradesh",
      Jabalpur: "Madhya Pradesh",
      Gwalior: "Madhya Pradesh",
      Ujjain: "Madhya Pradesh",
      Sagar: "Madhya Pradesh",
      Dewas: "Madhya Pradesh",
      Satna: "Madhya Pradesh",
      Rewa: "Madhya Pradesh",
      Murwara: "Madhya Pradesh",
      Jhansi: "Madhya Pradesh",
      Kolkata: "West Bengal",
      Howrah: "West Bengal",
      Durgapur: "West Bengal",
      Asansol: "West Bengal",
      Siliguri: "West Bengal",
      Baranagar: "West Bengal",
      "North Dumdum": "West Bengal",
      "South Dumdum": "West Bengal",
      Uluberia: "West Bengal",
      Bhatpara: "West Bengal",
      Panihati: "West Bengal",
      Kamarhati: "West Bengal",
      "Rajpur Sonarpur": "West Bengal",
      Haldia: "West Bengal",
      Barasat: "West Bengal",
      Bally: "West Bengal",
      Maheshtala: "West Bengal",
      Bardhaman: "West Bengal",
      Kulti: "West Bengal",
      Patna: "Bihar",
      Gaya: "Bihar",
      Bhagalpur: "Bihar",
      Muzaffarpur: "Bihar",
      Arrah: "Bihar",
      Purnia: "Bihar",
      Begusarai: "Bihar",
      "Bihar Sharif": "Bihar",
      Katihar: "Bihar",
      Darbhanga: "Bihar",
      Ranchi: "Jharkhand",
      Jamshedpur: "Jharkhand",
      Dhanbad: "Jharkhand",
      Bokaro: "Jharkhand",
      Rourkela: "Odisha",
      Bhubaneswar: "Odisha",
      Cuttack: "Odisha",
      Berhampur: "Odisha",
      Sambalpur: "Odisha",
      Ludhiana: "Punjab",
      Amritsar: "Punjab",
      Jalandhar: "Punjab",
      Bathinda: "Punjab",
      Patiala: "Punjab",
      Chandigarh: "Chandigarh",
      Rohtak: "Haryana",
      Sonipat: "Haryana",
      Panipat: "Haryana",
      Karnal: "Haryana",
      Dehradun: "Uttarakhand",
      Haridwar: "Uttarakhand",
      Srinagar: "Jammu & Kashmir",
      Jammu: "Jammu & Kashmir",
      Guwahati: "Assam",
      Silchar: "Assam",
      Bongaigaon: "Assam",
      Imphal: "Manipur",
      Aizawl: "Mizoram",
      Agartala: "Tripura",
      Raipur: "Chhattisgarh",
      Bhilai: "Chhattisgarh",
      Durg: "Chhattisgarh",
      Bilaspur: "Chhattisgarh",
      Korba: "Chhattisgarh",
      Kochi: "Kerala",
      Thiruvananthapuram: "Kerala",
      Kozhikode: "Kerala",
      Thrissur: "Kerala",
      Kollam: "Kerala",
      Pondicherry: "Puducherry",
      Ozhukarai: "Puducherry",
      Raichur: "Karnataka",
      Loni: "Uttar Pradesh",
      "Karawal Nagar": "Delhi",
      Mango: "Jharkhand",
      "Kirari Suleman Nagar": "Delhi",
      Gopalpur: "Odisha",
    };
    const citiesPayload = citiesJson.map((name) => ({
      name,
      state: STATE_MAP[name] || "India",
    }));
    await bulkUpsertCities(citiesPayload);
    logger.info("Cities seeded successfully from JSON");
  } catch (err) {
    logger.warn("City seed warning — falling back to cache", {
      error: err.message,
    });
    await initCityCache();
  }
  try {
    const airportsJson = JSON.parse(
      await readFile(
        new URL("./modules/flights/data/airports.json", import.meta.url),
      ),
    );
    await bulkUpsertAirports(airportsJson);
    logger.info("Airports seeded successfully from JSON");
  } catch (err) {
    logger.warn("Airport seed warning — falling back to cache", {
      error: err.message,
    });
    await initAirportCache();
  }
  startCronJobs();
  app.listen(process.env.PORT, () => {
    logger.info(`Payanam API running on port ${process.env.PORT}`, {
      port: process.env.PORT,
      env: process.env.NODE_ENV || "development",
    });
  });
}
start().catch((err) => {
  logger.error("Fatal: failed to start server", {
    error: err.message,
    stack: err.stack,
  });
  process.exit(1);
});
